version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-python-dependencies"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
